### PR TITLE
Minor improvements to the UI

### PR DESCRIPTION
**Pull request by isatsam**
- Adds a "Open Mods folder" button for quicker access to it.
- Adds a short description to the filebrowser that is opened in Settings -> "Browse". (It unfortunately seems to wrap in a kind of an ugly way..)

### CODE REVIEW

**Comment by SurDno** [comment]
I believe I had a “Browse” description at some point but removed it specifically because of the wrapping issue. Unless that is fixed, I would prefer to have no description at all (as it is fairly obvious what the dialog does).

Also: could you keep your braces indentation to K&R style as in the rest of the project? I do not know which IDE you use, but you can configure e.g. Rider to adapt to current conventions in the project.

I will merge the pull request once there are no code style changes in the commits.

**Comment by isatsam** [comment]
@SurDno Hi! Fixed the code style in the two affected files. (Using VisualStudio which apparently reformats everything automatically however it sees fit...) The description is also removed now.

**Comment by SurDno** [comment]
Merged now, will be included in 0.0.10 at some point later this month.

**Comment by isatsam** [comment]
Great! Will try to get #3 submitted as well by then (likely later this week).

**Pull request merged**
